### ISSUE TITLE
Add Default Campaign Social Imagery to Site

### ISSUE THREAD

**Issue by ryanrutan** [tx10indivisible/tx10indivisible.github.io#10]
http://www.tx10indivisible.us/img/campaigns/article.png
http://www.tx10indivisible.us/img/campaigns/cta.png
http://www.tx10indivisible.us/img/campaigns/event.png
http://www.tx10indivisible.us/img/campaigns/postcards.png
http://www.tx10indivisible.us/img/campaigns/letters.png
http://www.tx10indivisible.us/img/campaigns/special.png
http://www.tx10indivisible.us/img/campaigns/generic.png

**Comment by chip-rosenthal** [comment]
Can you explain what these links are?

**Comment by ryanrutan** [comment]
These are where we need to put the images, when we get the created.
