### ISSUE TITLE
front page banner

### ISSUE THREAD

**Issue by chip-rosenthal** [tx10indivisible/tx10indivisible.github.io#22]
(Cleaning out tasks there were in my backlog queue.)

There is an updated banner image in the tx10indivisible-graphics repo (TX-10 Borderless.png) that was contributed for the front page, to replace the current &lt;h1> text title. (When this is done it would be super good to include "alt" text to be screen reader friendly.)

This is addition to the logo that's already in the page header.

**Comment by ryanrutan** [comment]
Proposed solution posted in #tech ... waiting on confirmation before merging pull request.
