### ISSUE TITLE
add signup form widget

### ISSUE THREAD

**Issue by chip-rosenthal** [tx10indivisible/tx10indivisible.github.io#6]
Shortly, we will need to add a signup form widget to the website.

This will be used for an email list signup. At this time, the exact mailing service and form content has not been identified. The immediate task is figure out how to put the widget (can mock up with a simple form with fields for name and email) on the site.

It would be ideal if there's a way to put it in the page layout for the site so it appears everywhere -- in a visible but not too intrusive way.

Once we get details on the mailing network we can fill out the widget content.

**Comment by eponvert** [comment]
Shouldn't be hard, just a matter of updating the main page template so the link you want appears on all pages. I'll take this one if I'm around when details are available.

**Comment by chip-rosenthal** [comment]
Do you think you can do a mockup form with firstname, lastname, email?

I can view from your repo.

**Comment by chip-rosenthal** [comment]
Elias - can you assign yourself to this ticket to claim it?

**Comment by chip-rosenthal** [comment]
I added _includes/email_signup_form.html with an example widget that does email signups.

The Liquid code to include this is: 

`{% include email_signup_form.html %}`

The final implementation doesn't need to be this widget, it's just an example of something that works.

Would somebody be willing to add it to the web site, at least the front page. I actually think that page would work better as a two-column design, with news in one column and other info (including signup widget) in the other.

**Comment by chip-rosenthal** [comment]
done
